"""Added is_voided flag and updated relationships

Revision ID: c89d83b59291
Revises: 42e511a7077d
Create Date: 2025-03-07 10:33:22.895485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c89d83b59291'
down_revision = '42e511a7077d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_voided', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('is_voided')

    # ### end Alembic commands ###
